### PR TITLE
Organization statuses

### PR DESCRIPTION
**Pull request by Jnegrier**
When an org is created, is set with the status `Draft` by default there is also a new endpoint to return all the status an org can have.

The Publish and Deactivate states will be handled on a follow-up PR

### CODE REVIEW

**Review by opishcheiko — APPROVED** [review]
wow, it's a separate table, serious stuff.

let's think of the user flow. I have this in mind:
- a potential org sends a request
- an admin iin the Admin panel sees a pending org, sets it as "verified"
- the main contact gets an email with the org admin url + credentials (how do we enable org admin but not enable the org site ?)
- he goes to org admin -> fills all the necessary fields -> clicks "Preview" -> sees the homepage kinda greyed out -> clicks Publish (we should also allow him to go back and update the draft org)


What do you think? I am open for suggestions

**Comment by opishcheiko** [comment]
Another thought: why don't we have 4 statuses: pending, draft, published, disabled? And have them together with other org information?
I know we built the "verified" status already as a separate thing, but it can be a part of the flow maybe? 
So we can call the same endpoint all the time, when we upgrade the org/change the status/verify/disable/publish, by just passing the status we want depending on the situation and the full org details.
Though maybe it doesn't make sense to rewrite the stuff.

**Comment by Jnegrier** [comment]
@opishcheiko it doesn't sound bad, but what status should we set, if an organization lost its verification? Imagine that we get fraudulent reports or something, how are we gonna deal with those cases? maybe another status?

**Comment by opishcheiko** [comment]
if it's a published org, the admin can disable it. Would there be a case when org is not verified but still live? Since there is a comments field there, they can disable it saying "to be looked at" or something like that.
But yeah, I understood what you mean

**Comment by Jnegrier** [comment]
> if it's a published org, the admin can disable it. Would there be a case when org is not verified but still live? Since there is a comments field there, they can disable it saying "to be looked at" or something like that.
> But yeah, I understood what you mean

Yeah, it makes sense to me, seems like a natural flow, I will remove the verified field, and add the new status. I was thinking that we could even another status for when the Org need to be reverified, something like "On revision", which maybe could let the org to be still published, but it's kinda suspicious or something

**Comment by opishcheiko** [comment]
aa, good idea. Maybe like "possible issue" or something. I like this concept of many statuses for now. That admins will have the flexibility to set "resolution" in a way. Maybe there are some caveats, who knows

**Comment by Jnegrier** [comment]
> aa, good idea. Maybe like "possible issue" or something. I like this concept of many statuses for now. That admins will have the flexibility to set "resolution" in a way. Maybe there are some caveats, who knows

New status `Under Review` added, also all the endpoint using the verified field were refactored, everything should be working just fine.

There a strange error about CORS when updating the status from the frontend, couldn't figure out the cause. It actually happened before as well, and got fixed by doing nothing, maybe its something residual on the environment

**Review by opishcheiko — APPROVED** [review]

**Pull request merged**
