### PR TITLE
Collaborators, Beneficiaries and organisation integration

### PR DESCRIPTION
**Pull request by Jnegrier**
New collaborators and beneficiaries are now related to an organization.

There are also two new endpoints to get collaborator and beneficiaries given an org id:

`/beneficiaries/organization_id/{org_id}`
`/collaborators/organization_id/{org_id}`

### CODE REVIEW

**Review by opishcheiko — APPROVED** [review]
Hi Juan, thanks a lot, a very needed fix!
Would that mean that in the big org payload we'll now have all beneficiaries and collaborators listed?

**Comment by Jnegrier** [comment]
> Hi Juan, thanks a lot, a very needed fix!
> Would that mean that in the big org payload we'll now have all beneficiaries and collaborators listed?

Thanks Sasha, 
That's a very good question, that's big org response is not going to include the list of collaborators and beneficiaries, the main reason is that when using the native object, it's creating a recursive call, which ends in an infinite loop.
I can refactor it to return collaborators and beneficiaries as part of the response tho, pls let me know if that something you would need

**Comment by opishcheiko** [comment]
@Jnegrier  I would prefer to have everything in one endpoint, so I can get a server side rendering without a need to do any more calls. 
But it's okay, it's great to have it anyway, I don't think there is a need for refactor. Thanks!!

**Comment by Jnegrier** [comment]
> @Jnegrier I would prefer to have everything in one endpoint, so I can get a server side rendering without a need to do any more calls.
> But it's okay, it's great to have it anyway, I don't think there is a need for refactor. Thanks!!

That's makes a lot of sense. Don't worry, I need to refactor that payload anyway, cause its the native object from hibernate for the moment, so its not a problem to refactor it

**Pull request merged**
